import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const catalog = JSON.parse(read('data/articles.json'));
const html = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const md = s => String(s).replace(/[\\[\]]/g, '\\$&');
const byId = new Map(catalog.articles.map(a => [a.id, a]));
assert.equal(byId.size, catalog.articles.length, 'Duplicate article ID');
const topicIds = new Set(catalog.topics.map(t => t.id));
assert.equal(topicIds.size, catalog.topics.length);
const files = fs.readdirSync(path.join(root,'docs')).filter(f => /^\d+\.md$/.test(f)).map(f => Number(f.slice(0,-3))).sort((a,b)=>a-b);
assert.deepEqual([...byId.keys()].sort((a,b)=>a-b), files, 'Every numbered article needs metadata');
for (const a of catalog.articles) {
  assert.ok(Number.isInteger(a.id) && a.id > 0);
  for (const field of ['title','originalTitle','versionNote']) assert.ok(typeof a[field] === 'string' && a[field].trim(), `${a.id}: ${field}`);
  assert.ok(/[\u3400-\u9fff]/.test(a.title), `${a.id}: missing Chinese title`);
  assert.ok(a.topics.length && a.topics.every(t => topicIds.has(t)), `${a.id}: topic`);
  assert.ok(catalog.types[a.type] && Array.isArray(a.aliases) && a.aliases.every(x=>typeof x==='string'));
  assert.equal(new URL(a.source.url).protocol, 'https:');
  assert.ok(a.source.label && a.validation.note);
  assert.ok(['tested','not-recorded'].includes(a.validation.status));
  if (a.validation.status === 'tested') {
    assert.ok(a.validation.record && a.validation.date, `${a.id}: evidence required`);
    assert.ok(fs.existsSync(path.join(root, a.validation.record.slice(1))));
  }
}
for (const p of catalog.paths) assert.ok(p.articles.length && p.articles.every(id=>byId.has(id)));
assert.ok(catalog.featured.every(id=>byId.has(id)));
const link = id => `[${md(byId.get(id).title)}](/docs/${id}.md)`;
const articleLink = a => `<a href="#/docs/${a.id}">${html(a.title)}</a>`;
const banner = '<!-- Generated by maintenance/build-catalog.mjs. Edit data/articles.json instead. -->\n\n';
const outputs = new Map();
let sidebar = '* **PostgreSQL Howto 中文版**\n  * [首页](/README.md)\n  * [查找文章](/docs/find.md)\n  * [专题索引](/docs/topics.md)\n  * [推荐路径](/docs/paths.md)\n  * [会议精选](/docs/conferences.md)\n';
let topics = '# 专题索引\n\n按技术问题组织文章；同一篇可以属于多个专题。\n\n<div class="topic-grid">\n';
for (const t of catalog.topics) {
  const entries = catalog.articles.filter(a=>a.topics.includes(t.id));
  topics += `<a class="topic-card" href="#/docs/topics?id=topic-${t.id}" data-docs-route="/docs/topics?id=topic-${t.id}"><strong>${html(t.title)} · ${entries.length}</strong><span>${html(t.description)}</span></a>\n`;
  sidebar += `\n* **${t.title}**\n` + catalog.articles.filter(a=>a.topics[0] === t.id).map(a=>`  * [${a.id}. ${md(a.title)}](/docs/${a.id}.md)`).join('\n') + '\n';
}
topics += '</div>\n';
for (const t of catalog.topics) topics += `\n<span id="topic-${t.id}"></span>\n\n## ${t.title}\n\n${t.description}\n\n` + catalog.articles.filter(a=>a.topics.includes(t.id)).map(a=>`- ${link(a.id)} · ${catalog.types[a.type]}`).join('\n') + '\n';
outputs.set('_sidebar.md',banner+sidebar);
outputs.set('docs/topics.md',banner+topics);
outputs.set('docs/paths.md', banner+'# 推荐路径\n\n按问题选择一条路径，从判断依据读到具体操作。\n\n<div class="path-grid">\n'+catalog.paths.map(p=>`<section class="path-card"><h2>${html(p.title)}</h2><p>${html(p.description)}</p><ol>${p.articles.map(id=>`<li>${articleLink(byId.get(id))}</li>`).join('')}</ol></section>`).join('\n')+'\n</div>\n');
outputs.set('docs/conferences.md',banner+'# 会议精选\n\n按会议回溯来源，文章同时归入对应技术专题。\n'+catalog.articles.filter(a=>a.type==='conference').sort((a,b)=>b.source.date.localeCompare(a.source.date)).map(a=>`\n## ${a.source.event}\n\n### ${link(a.id)}\n\n${a.source.label} · ${a.source.date}\n\n原题：${a.originalTitle}\n\n${a.versionNote} ${a.validation.note}\n\n[原始材料](${a.source.url}) · ${link(a.id)}\n`).join(''));
outputs.set('docs/find.md',banner+'# 查找文章\n\n<div class="article-finder" data-finder></div>\n\n[浏览全部专题](/docs/topics.md) · [推荐路径](/docs/paths.md)\n');
const discovery = `<div class="article-finder" data-finder data-home></div>\n<div class="problem-links" aria-label="按问题查找">${catalog.problems.map(p=>`<a href="#/docs/find?q=${encodeURIComponent(p.query)}">${html(p.title)}</a>`).join('')}</div>`;
const recent = catalog.featured.map(id=>byId.get(id));
for (const a of recent) assert.ok(/^\d{4}-\d{2}-\d{2}$/.test(a.addedOn) && new Date(a.addedOn).toISOString().slice(0,10) === a.addedOn, `${a.id}: valid addedOn required`);
recent.sort((a,b)=>b.addedOn.localeCompare(a.addedOn) || b.id-a.id);
const featured = '## 最近收录\n\n<ul class="recent-articles">\n'+recent.map(a=>`<li>${articleLink(a)}<span>${catalog.types[a.type]} · 收录于 <time datetime="${a.addedOn}">${a.addedOn}</time></span></li>`).join('\n')+'\n</ul>\n\n[全部专题](/docs/topics.md) · [推荐路径](/docs/paths.md) · [会议精选](/docs/conferences.md)\n';
const template = read('maintenance/home-template.md');
assert.equal(template.split('<!-- HOME_DISCOVERY -->').length,2);
assert.equal(template.split('<!-- HOME_FEATURED -->').length,2);
outputs.set('README.md',banner+template.replace('<!-- HOME_DISCOVERY -->',discovery).replace('<!-- HOME_FEATURED -->',featured));
const index = catalog.articles.map(a=>({id:a.id,text:read(`docs/${a.id}.md`).replace(/<!--[^]*?-->/g,' ').replace(/https?:\/\/[^\s)]+/g,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}));
const revision = createHash('sha256').update(JSON.stringify(catalog)+JSON.stringify(index)).digest('hex').slice(0,16);
outputs.set('data/search-index.json', JSON.stringify({revision,articles:index})+'\n');
outputs.set('scripts/catalog-data.js', '// Generated; do not edit.\nwindow.HowtoCatalog = '+JSON.stringify({...catalog,revision}).replaceAll('<','\\u003c')+';\n');
let entry = read('index.html');
for (const asset of ['scripts/catalog-data.js','scripts/search-core.js','scripts/reading.js','scripts/comments.js','styles/custom.css','styles/reading.css']) {
  const hash=createHash('sha256').update(outputs.get(asset) || read(asset)).digest('hex').slice(0,16);
  const pattern=new RegExp('(\\./'+asset.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')(?:\\?v=[^"\\s]+)?(?=")','g');
  assert.ok(pattern.test(entry),'Missing asset reference: '+asset);
  pattern.lastIndex=0;
  entry=entry.replace(pattern,'$1?v='+hash);
}
outputs.set('index.html',entry);
let stale = false;
for (const [file,text] of outputs) {
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(path.join(root,file)) || read(file)!==text) { console.error('Out of date:',file); stale=true; }
  } else {
    fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});
    fs.writeFileSync(path.join(root,file),text);
  }
}
if (stale) process.exitCode=1;
else console.log(`${catalog.articles.length} article records validated; ${outputs.size} generated files ${process.argv.includes('--check')?'verified':'updated'} (${revision}).`);
